database:
  host: localhost
  port: 5432
  name: postgres
  user: postgres
  password: test1!
  # host: ${DB_HOST:-localhost}
  # port: ${DB_PORT:-5432}
  # name: ${DB_NAME:-market_data}
  # user: ${DB_USER:-your_username}
  # password: ${DB_PASSWORD}


webhook_url_his: 'https://hook.eu2.make.com/2jgaubiw451gzfflwxpyink1mpnelw3e'
webhook_url_upnote: 'https://hook.eu2.make.com/1y8uzprjp9ckz1hwrq2jc1s91in01nxn'